import type { Metadata } from "next";
import { company } from "@/data/company";
import { PageShell } from "@/components/catalog/page-shell";
import { InstagramIcon } from "@/components/brand-icons";

export const metadata: Metadata = { title: "Contacto", description: "Contactá a Districe para consultar repuestos, accesorios y líneas automotor." };
export default function ContactPage() {
  return <PageShell><section className="contact-opening section-shell"><div className="contact-heading"><p className="eyebrow">Contacto / Atención comercial</p><h1>Tu próxima consulta<br /><i>empieza acá.</i></h1><p>Contanos qué familia, marca o línea estás buscando. Te ayudamos a orientar tu pedido.</p></div><div className="contact-channels"><p className="eyebrow">Escribinos o llamanos</p><a className="contact-main-email" href={`mailto:${company.email}`}><small>Email</small>{company.email}<span aria-hidden="true">↗</span></a><div className="contact-phones">{[company.phone, ...company.mobiles].map((phone, index) => <a key={phone} href={`tel:${phone.replace(/[^\d+]/g, "")}`}><small>{index === 0 ? "Teléfono" : `Celular ${index}`}</small>{phone}<span aria-hidden="true">↗</span></a>)}</div><a className="social-link" href={company.instagram} target="_blank" rel="noreferrer"><InstagramIcon /> Instagram de Districe <span aria-hidden="true">↗</span></a></div></section><section className="contact-guidance section-shell"><p className="eyebrow">Una consulta bien orientada</p><h2>Encontrar la línea adecuada<br />es el primer paso.</h2><p>Escribinos por email o llamanos para consultar productos y disponibilidad.</p><a className="button" href={`mailto:${company.email}?subject=Consulta%20comercial%20Districe`}>Escribir a Districe ↗</a><p className="contact-shipping">{company.logistics}</p></section></PageShell>;
}
