import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { brandsForFamily, getFamily, productFamilies } from "@/data/catalog";
import { familyAssets } from "@/data/assets";
import { BrandLogo } from "@/components/brand-logo";
import { PageShell } from "@/components/catalog/page-shell";

export function generateStaticParams() { return productFamilies.map((family) => ({ slug: family.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const family = getFamily((await params).slug); return { title: family ? `${family.name} | Productos` : "Productos", description: family?.description }; }
export default async function FamilyPage({ params }: { params: Promise<{ slug: string }> }) { const family = getFamily((await params).slug); if (!family) notFound(); const familyBrands = brandsForFamily(family.slug); const visual = familyAssets[family.slug]; return <PageShell><section className={`family-opening ${familyBrands.length ? "family-opening-split" : "family-opening-wide"} family-opening-${family.slug}`}><div className="family-opening-photo"><Image src={visual.src} fill sizes={familyBrands.length ? "(max-width: 800px) 100vw, 55vw" : "100vw"} alt={visual.alt} priority /></div><div className="family-opening-copy"><Link className="eyebrow" href="/productos">Productos / Familia {family.index}</Link><h1>{family.name}</h1><p>{family.description}</p><a className="text-link" href="#lineas">Explorar esta familia ↓</a></div></section><section className="family-detail section-shell" id="lineas"><aside><p className="eyebrow">Catálogo Districe / {family.index}</p><p>{family.description}</p><Link className="catalog-back" href="/productos">← Todas las familias</Link></aside><div><p className="eyebrow"><span /> {familyBrands.length ? "Marcas y líneas" : "Consulta comercial"}</p><h2>{familyBrands.length ? "Una familia, distintas especialidades." : "Encontrá la línea adecuada para tu operación."}</h2>{familyBrands.length ? <div className="family-brand-list">{familyBrands.map((brand) => <article key={brand.slug}><Link href={`/marcas/${brand.slug}`}><span className={`family-brand-logo brand-surface-${brand.slug}`}><BrandLogo slug={brand.slug} decorative sizes="88px" /></span><span className="family-brand-copy"><b className="sr-only">{brand.name}</b><small>{brand.lines.join(" · ") || "Difusores de auto · Ver catálogo"}</small></span><span className="family-brand-arrow">↗</span></Link></article>)}</div> : <p className="catalog-copy">Contanos qué necesitás para tu trabajo. El equipo comercial te orienta sobre las líneas y la disponibilidad de esta familia.</p>}<Link className="button" href="/contacto">Solicitar cotización ↗</Link><Link className="catalog-back" href="/productos">Ver todas las familias</Link></div></section></PageShell>; }
