"use client";

import Image from "next/image";
import { AnimatePresence, motion, useReducedMotion } from "motion/react";
import { useEffect, useRef, useState } from "react";
import { brands, productFamilies, searchEntries, type SearchEntry } from "@/data/catalog";
import { company } from "@/data/company";

const navItems = [{ label: "Marcas", href: "#marcas" }, { label: "Empresa", href: "#empresa" }, { label: "Contacto", href: "#contacto" }];

function SearchOverlay({ close }: { close: () => void }) {
  const [query, setQuery] = useState("");
  const [active, setActive] = useState(0);
  const input = useRef<HTMLInputElement>(null);
  const reduced = useReducedMotion();
  useEffect(() => { input.current?.focus(); }, []);
  const results = query ? searchEntries.filter((item) => `${item.label} ${item.detail}`.toLocaleLowerCase("es").includes(query.toLocaleLowerCase("es"))) : searchEntries.slice(0, 6);
  const choose = (entry: SearchEntry) => { if (entry.target.startsWith("/")) window.location.assign(entry.target); else document.querySelector(entry.target)?.scrollIntoView({ behavior: "smooth" }); close(); };
  const groups = ["Familia", "Marca", "Línea"] as const;
  return <motion.div className="search-overlay" initial={reduced ? { opacity: 0 } : { opacity: 0, y: -12 }} animate={{ opacity: 1, y: 0 }} exit={reduced ? { opacity: 0 } : { opacity: 0, y: -12 }} transition={{ duration: .22 }} role="dialog" aria-modal="true" aria-label="Buscar productos" onKeyDown={(event) => { if (event.key === "Escape") close(); if (event.key === "ArrowDown") { event.preventDefault(); setActive((active + 1) % results.length); } if (event.key === "ArrowUp") { event.preventDefault(); setActive((active - 1 + results.length) % results.length); } if (event.key === "Enter" && results[active]) choose(results[active]); }}><div className="search-dialog"><div className="search-dialog-input"><svg aria-hidden="true" viewBox="0 0 24 24"><circle cx="10.8" cy="10.8" r="6.2" /><path d="m16 16 4.2 4.2" /></svg><input ref={input} value={query} onChange={(event) => { setQuery(event.target.value); setActive(0); }} placeholder="¿Qué necesitás encontrar?" /><button onClick={close}>Esc</button></div><div className="search-dialog-results">{results.length ? groups.map((group) => { const entries = results.filter((entry) => entry.type === group); return entries.length ? <section key={group}><p>{group === "Familia" ? "Familias" : `${group}s`}</p>{entries.map((entry) => { const index = results.indexOf(entry); return <button key={entry.id} className={index === active ? "active" : ""} onMouseEnter={() => setActive(index)} onClick={() => choose(entry)}><span><b>{entry.label}</b><small>{entry.detail}</small></span><em>{entry.type}</em><i>↗</i></button>; })}</section> : null; }) : <div className="search-empty"><b>Sin resultados aún.</b><span>Probá con una familia, una marca o una línea.</span></div>}</div><footer><span>↑↓ para navegar</span><span>↵ para abrir</span><span>Esc para cerrar</span></footer></div></motion.div>;
}

export function Header() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [megaOpen, setMegaOpen] = useState(false);
  const [searchOpen, setSearchOpen] = useState(false);
  const [compact, setCompact] = useState(false);
  const reduced = useReducedMotion();
  useEffect(() => { const onScroll = () => setCompact(window.scrollY > 18); const onKey = (event: KeyboardEvent) => { if (event.key === "/" && !(event.target instanceof HTMLInputElement)) { event.preventDefault(); setSearchOpen(true); } }; window.addEventListener("scroll", onScroll, { passive: true }); window.addEventListener("keydown", onKey); return () => { window.removeEventListener("scroll", onScroll); window.removeEventListener("keydown", onKey); }; }, []);
  return <><header className={`site-header ${compact ? "is-compact" : ""}`}><div className="header-inner"><a href="#inicio" className="brand" aria-label="Districe, inicio"><Image src="/brand/districe-logo.jpg" width={2161} height={728} priority alt="Districe — Repuestos y Accesorios Automotor" /></a><nav className="desktop-nav" aria-label="Navegación principal"><button aria-expanded={megaOpen} aria-controls="products-mega" onClick={() => setMegaOpen(!megaOpen)}>Productos <span>+</span></button>{navItems.map((item) => <a key={item.href} href={item.href}>{item.label}</a>)}</nav><div className="header-actions"><button className="search-trigger" onClick={() => setSearchOpen(true)} aria-haspopup="dialog"><svg aria-hidden="true" viewBox="0 0 24 24"><circle cx="10.8" cy="10.8" r="6.2" /><path d="m16 16 4.2 4.2" /></svg><span>Buscar</span><kbd>/</kbd></button><a className="quote-button desktop-quote" href="#contacto">Solicitar cotización <span>↗</span></a><button className="menu-button" aria-label={menuOpen ? "Cerrar menú" : "Abrir menú"} aria-expanded={menuOpen} onClick={() => setMenuOpen(!menuOpen)}><i /><i /></button></div></div><AnimatePresence>{megaOpen && <motion.div id="products-mega" className="mega-menu" initial={reduced ? { opacity: 0 } : { opacity: 0, y: -8 }} animate={{ opacity: 1, y: 0 }} exit={reduced ? { opacity: 0 } : { opacity: 0, y: -8 }} transition={{ duration: .2 }}><div className="mega-inner"><div><p>Explorar productos</p><h2>Familias para<br />cada necesidad.</h2><button className="text-link" onClick={() => { setMegaOpen(false); window.location.hash = "#familias"; }}>Ver todas <span>↗</span></button></div><div className="mega-families">{productFamilies.map((family) => <a href="#familias" onClick={() => setMegaOpen(false)} key={family.slug}><span>{family.index}</span>{family.name}<b>↗</b></a>)}</div><div className="mega-aside"><p>Marcas destacadas</p>{brands.map((brand) => <a href="#marcas" onClick={() => setMegaOpen(false)} key={brand.slug}>{brand.name}</a>)}<button onClick={() => { setMegaOpen(false); setSearchOpen(true); }}>Buscar una línea <span>→</span></button></div></div></motion.div>}</AnimatePresence>{menuOpen && <div className="mobile-menu"><button className="mobile-search" onClick={() => { setMenuOpen(false); setSearchOpen(true); }}>Buscar productos, marcas o líneas <span>↗</span></button><nav aria-label="Navegación móvil"><a href="#familias" onClick={() => setMenuOpen(false)}><span>01</span>Productos<b>↗</b></a>{navItems.map((item, index) => <a key={item.href} href={item.href} onClick={() => setMenuOpen(false)}><span>0{index + 2}</span>{item.label}<b>↗</b></a>)}</nav><a className="quote-button" href={company.whatsappHref} target="_blank" rel="noreferrer">Consultar por WhatsApp <span>↗</span></a><p>{company.contactStatus}</p></div>}</header><AnimatePresence>{searchOpen && <SearchOverlay close={() => setSearchOpen(false)} />}</AnimatePresence></>;
}
