"use client";

import { useRef } from "react";
import { brands, productFamilies } from "@/data/catalog";
import { company } from "@/data/company";
import { Header } from "./header";

function ArrowIcon() { return <svg aria-hidden="true" viewBox="0 0 24 24"><path d="M5 12h13M13 6l6 6-6 6" /></svg>; }

export function Home() {
  const trackRef = useRef<HTMLDivElement>(null);
  const scrollFamilies = (direction: number) => trackRef.current?.scrollBy({ left: direction * 340, behavior: "smooth" });
  return <main id="inicio"><Header />
    <section className="hero section-shell" aria-labelledby="hero-title"><div className="hero-copy"><p className="eyebrow"><span /> Distribución mayorista · Desde {company.founded}</p><h1 id="hero-title">Repuestos y accesorios <i>para avanzar.</i></h1><p className="hero-description">Districe acompaña al mercado automotor con una selección especializada de productos, marcas y líneas para el canal profesional.</p><div className="hero-actions"><a className="button button-primary" href="#familias">Explorar productos <ArrowIcon /></a><a className="text-link" href="#contacto">Hacer una consulta <ArrowIcon /></a></div></div><div className="hero-stage" aria-label="Composición gráfica de producto automotor"><div className="stage-grid" /><div className="stage-ring ring-one" /><div className="stage-ring ring-two" /><div className="stage-label label-top">DISTRICE / 1987—</div><div className="stage-label label-bottom">CANAL PROFESIONAL</div><div className="product-object"><div className="product-cap" /><div className="product-band">DISTRICE</div><div className="product-mark">D</div></div><div className="hero-stat"><b>Desde<br />1987</b><span>en el mercado de repuestos y accesorios automotor</span></div></div></section>
    <section id="familias" className="families-section" aria-labelledby="familias-title"><div className="section-shell"><div className="section-heading"><div><p className="eyebrow"><span /> Explorar por necesidad</p><h2 id="familias-title">Familias que mueven<br /><i>tu operación.</i></h2></div><div className="track-controls"><p>Deslizá para recorrer</p><button onClick={() => scrollFamilies(-1)} aria-label="Ver familias anteriores">←</button><button onClick={() => scrollFamilies(1)} aria-label="Ver familias siguientes">→</button></div></div></div><div className="family-track" ref={trackRef} tabIndex={0} aria-label="Familias de producto">{productFamilies.map((family) => <a className={`family-card tone-${family.tone}`} href="#contacto" key={family.slug}><div className="card-top"><span>{family.index}</span><ArrowIcon /></div><div className="family-art"><i /><i /><i /></div><div><h3>{family.name}</h3><p>{family.description}</p>{family.lines.length > 0 && <small>{family.lines.slice(0, 3).join(" · ")}</small>}</div></a>)}</div><div className="section-shell family-foot"><p>Las familias surgen de la taxonomía pública actual de Districe.</p><a className="text-link" href="#contacto">No encontrás lo que buscás <ArrowIcon /></a></div></section>
    <section id="marcas" className="brands section-shell" aria-labelledby="marcas-title"><div className="brand-intro"><p className="eyebrow"><span /> Selección de marcas</p><h2 id="marcas-title">Conocé las líneas<br />que distribuimos.</h2><p>Presentamos marcas confirmadas en las fuentes públicas actuales. La selección se ampliará con validación comercial.</p><a className="text-link" href="#contacto">Consultar por una marca <ArrowIcon /></a></div><div className="brand-list">{brands.map((brand, index) => <article className="brand-row" key={brand.slug}><span>0{index + 1}</span><div><h3>{brand.name}</h3><p>{brand.description}</p></div><ul>{brand.lines.slice(0, 3).map((line) => <li key={line}>{line}</li>)}</ul><a href="#contacto" aria-label={`Consultar por ${brand.name}`}><ArrowIcon /></a></article>)}</div></section>
    <section id="empresa" className="trust-section"><div className="section-shell trust-grid"><div className="trust-statement"><p className="eyebrow"><span /> La experiencia detrás del suministro</p><h2>Una trayectoria construida <i>en movimiento.</i></h2><p>Districe comenzó su actividad en 1987 con distribución mayorista de filtros para línea liviana y pesada. Con el tiempo amplió su oferta para acompañar las necesidades del mercado automotor.</p></div><div className="trust-points">{company.differentiators.map((item, index) => <div key={item}><span>0{index + 1}</span><p>{item}</p></div>)}<small>Conceptos declarados en el sitio actual; sin métricas no verificadas.</small></div></div></section>
    <section className="coverage section-shell"><div><p className="eyebrow"><span /> Operación</p><h2>La respuesta correcta empieza con una buena conversación.</h2></div><div className="coverage-card"><div className="coverage-lines"><i /><i /><i /><i /><i /></div><p>La cobertura y las condiciones logísticas serán comunicadas cuando estén confirmadas.</p><span>Información en actualización</span></div></section>
    <section id="contacto" className="contact-section"><div className="section-shell contact-grid"><div><p className="eyebrow"><span /> Contacto comercial</p><h2>¿Buscás una línea<br />para tu negocio?</h2></div><div className="contact-action"><p>Contanos qué necesitás. El equipo comercial te orientará hacia la familia, marca o línea adecuada.</p><a className="button button-light" href={company.whatsappHref} target="_blank" rel="noreferrer">Consultar por WhatsApp <ArrowIcon /></a><a className="contact-email" href={`mailto:${company.email}`}>{company.email} <ArrowIcon /></a></div></div></section>
    <footer className="site-footer"><div className="section-shell footer-top"><a href="#inicio" className="footer-brand">DISTRICE<span>Repuestos y Accesorios Automotor</span></a><div className="footer-links"><a href="#familias">Productos</a><a href="#marcas">Marcas</a><a href="#empresa">Empresa</a><a href="#contacto">Contacto</a></div><div className="footer-contact"><a href={`mailto:${company.email}`}>{company.email}</a><a href="tel:+543514895039">{company.phone}</a><a href={company.whatsappHref} target="_blank" rel="noreferrer">WhatsApp comercial ↗</a></div></div><div className="section-shell footer-bottom"><span>© {new Date().getFullYear()} Districe</span><span>{company.contactStatus}</span><span>Desarrollo por Broco Solutions</span></div></footer>
  </main>;
}
